### PR TITLE
[Code128] Handle Set C in text font

### PR DESCRIPTION
**Pull request by khaledhosny**
… and other small fixes I needed to be able to build the fonts locally.

### CODE REVIEW

**Comment by davelab6** [comment]
> fontbakery --fix-dsig is gone?

Yes, but moved to https://github.com/googlefonts/tools/blob/master/bin/gftools-fix-dsig.py

**Comment by davelab6** [comment]
Anyway its so simple I think its fine to duplicate the core code here :) The GFT one isn't going to change

**Comment by graphicore** [comment]
LGTM so far is this ready to be merged? Also, please poke me when a new version is due.

**Comment by khaledhosny** [comment]
I think it is ready. I did some basic testing with all combination of numbers and non-numbers  I can think of and it worked. Dave might want to do more testing, though.

**Comment by graphicore** [comment]
Ok, cool. I'll merge it now and will have a look at the fonts when it's time for the release (is it?).

**Pull request merged**
